describe('Vetty CMS Test', function() {
  it('Visits the stage client url', function() {
  cy.viewport(1600,1200)
  cy.visit('https://stgclient.vetty.co')
  cy.get('#email').type('farha.client+10@gmail.com')
  cy.get('#ssn').type('1234567')
  cy.get('.login-button-container > .form-control').click()
  cy.wait(20000)
  cy.get('.client-nav-item-btn').click()
  cy.wait(10000)
  cy.get('#firstname').type('test')
  cy.wait(5000)
  cy.get('#lastname').type('eighteen')
  cy.wait(5000)
  cy.get('#email').type('monnowahann-7124@yopmail.com')
  cy.wait(5000)
  cy.get('select[formcontrolname="costcenter"]').select('Ranchi')
  cy.wait(5000)
  cy.get('select[formcontrolname="selectedPackage"]').select('SSN check')
  cy.wait(5000)
  cy.get(':nth-child(2) > .mx-auto').click()
  cy.wait(5000)
  cy.get('app-account-dropdown > .dropdown > #dropdownBasic1 > div').click()
  cy.wait(2000)
  cy.get('app-account-dropdown > .dropdown > .dropdown-menu > :nth-child(2)').click()
  cy.wait(2000)
  });
  });